# SPDX-FileCopyrightText: 2020-2026 Dimitrij Kotrev
#
# SPDX-License-Identifier: CC0-1.0

repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v2.1.0
    hooks:
      - id: reuse
  - repo: https://github.com/pre-commit/mirrors-clang-format
    # Use a specific tag or SHA for 'rev'
    # Check the repository for the latest version tag (e.g., v16.0.6)
    rev: v21.1.6
    hooks:
      - id: clang-format
        # Optionally, specify which files to run on.
        # By default, it runs on C/C++ and related file types.
        # files: \.(c|cc|cxx|cpp|h|hpp|txx|ipp)$
